version: '3.7'
services:
    app:
        build: .
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - app
    redis:
        image: redis:3.2-alpine
        volumes:
            - redis_data:/data
volumes:
    redis_data:
